#!bash

# change these to your stack app's name and port
STACKNAME="phpfpm"
PORT="77777"

# change these to the domain and directory you want the stack to serve
DOMAIN1="mydomain.com"
APPDIR1="$HOME/apps/app1"

# change these as needed, nginx or apache, php versions 5.6, 7.3, 7.4, 8.0, 8.1, 8.2, 8.3, 8.4
SERVER_TYPE="nginx"
PHP_VERSION="8.3"

# no need to change these
PREFIX="$HOME/apps/$STACKNAME"
LOGDIR="$HOME/logs/apps/$STACKNAME"
